In [ ]:
# A single neuron that takes 4 inputs:
inputs=[1,2,3,4]
weights=[0.2,0.3,0.5,0.8]
bias=3
linear_summation=0

for i in range(len(inputs)):
    linear_summation+=inputs[i]*weights[i]

linear_summation+=bias
print(f"The output of the neuron is {linear_summation}")

The output of the neuron is 8.5


In [3]:
# Three neurons taking 4 inputs:
inputs=[1,2,3,4]
weights=[
    [0.2,0.3,0.5,0.8],
    [0.5,0.3,0.9,0.8],
    [0.2,0.5,0.5,0.2],
    [0.1,0.7,0.5,0.6]
]
bias=[3,4,5,7]

for i in range(3):
    linear_summation=0
    for j in range(len(inputs)):
        linear_summation+=inputs[j]*weights[i][j]
    linear_summation+=bias[i]
    print(f"The output of the neuron {i} is {linear_summation}")


The output of the neuron 0 is 8.5
The output of the neuron 1 is 11.0
The output of the neuron 2 is 8.5


So, this was using normal for loops, now we will see the magic of numpy. Since, it does element wise operation it is much faster than the for loops

In [5]:
import numpy as np

# A single neuron that takes 4 inputs using numpy:
inputs=[1,2,3,4]
weights=[0.2,0.3,0.5,0.8]
bias=3
linear_summation=np.dot(inputs,weights)+bias
print(f"The output of the neuron is {linear_summation}")

The output of the neuron is 8.5


In [7]:
# Three neurons taking 4 inputs using numpy:
inputs=[1,2,3,4]
weights=[
    [0.2,0.3,0.5,0.8],
    [0.5,0.3,0.9,0.8],
    [0.2,0.5,0.5,0.2],
    [0.1,0.7,0.5,0.6]
]
biases=[3,4,5,7]

linear_summation=np.dot(weights,inputs)+biases
print(linear_summation)

[ 8.5 11.   8.5 12.4]


In [8]:
# Three neurons taking 4 features and 3 rows (batch) using numpy:
inputs=[
    [1,2,3,4],
    [3,4,2,1],
    [2,7,8,9]
    ]
weights=[
    [0.2,0.3,0.5,0.8],
    [0.5,0.3,0.9,0.8],
    [0.2,0.5,0.5,0.2],
    [0.1,0.7,0.5,0.6]
]
biases=[3,4,5,7]

linear_summation=np.dot(inputs,np.array(weights).T)+biases
print(linear_summation)

[[ 8.5 11.   8.5 12.4]
 [ 6.6  9.3  8.8 11.7]
 [16.7 21.5 14.7 21.5]]
