In [1]:
import numpy as np

In [4]:
inputs=[
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
]
weights=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]
bias=[2,3,0.5]

output=np.dot(inputs,np.array(weights).T)+bias
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [6]:
inputs=[
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
]
weights1=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]
bias1=[2,3,0.5]

weights2=[
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [-0.44,0.73,-0.13]
]
bias2=[-1,2,-0.5]

output1=np.dot(inputs,np.array(weights).T)+bias1
output2=np.dot(output1,np.array(weights2).T)+bias2

print(output2)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
